{% set name = "jsonpp" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jmhodges/jsonpp/archive/{{ version }}.tar.gz
  sha256: dde8ea9b270a79cd2b2f40824f89abc5270bd360122d87ab04b4361c0015d941

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - jsonpp --help

about:
  home: https://github.com/jmhodges/jsonpp
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Command-line JSON pretty-printer
  dev_url: https://github.com/jmhodges/jsonpp

extra:
  recipe-maintainers:
    - danielnachun
